name: WakaTime Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Ejecución diaria
  workflow_dispatch:      # Permite ejecución manual
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Usa el PAT en lugar de GITHUB_TOKEN
